use_linked_list: linked_list.o use_linked_list.o
	gcc linked_list.o use_linked_list.o -Wall -o use_linked_list
	
linked_list.o: linked_list.h linked_list.c
	gcc -Wall -c linked_list.c linked_list.h

use_linked_list.o: linked_list.h use_linked_list.c
	gcc -Wall -c use_linked_list.c linked_list.h


clean:
        rm -f *.o